# Local RPM build spec for padctl — build from source on Fedora 44.
# This is a local-use copy of padctl.spec, adapted for building from a
# source tarball instead of downloading a prebuilt musl binary.
#
# IMPORTANT: Zig 0.16 (Fedora 44) fails to compile padctl. You need
# Zig 0.15.2 from https://ziglang.org/download/0.15.2/zig-x86_64-linux-0.15.2.tar.xz
#
# Usage:
#   1. Extract Zig 0.15.2 somewhere, e.g. /opt/zig-0.15.2/zig
#
#   2. Create a source tarball from the repo root:
#        git archive --format=tar.gz --prefix=padctl-0.1.16/ HEAD \
#          -o ~/rpmbuild/SOURCES/padctl-0.1.16.tar.gz
#
#   3. Build the RPM (point to the working Zig):
#        rpmbuild -bb contrib/copr/padctl-local.spec \
#          --define "zig_bin /opt/zig-0.15.2/zig"
#
#   To install the resulting RPM:
#        sudo dnf install ~/rpmbuild/RPMS/$(uname -m)/padctl-0.1.16-2.fc44.$(uname -m).rpm

# Zig-built binaries lack .note.gnu.build-id; skip debuginfo extraction.
%define debug_package %{nil}

Name:           padctl
Version:        0.1.18
Release:        1%{?dist}
Summary:        HID gamepad remapper with declarative TOML config

License:        LGPL-2.1-or-later
URL:            https://github.com/BANANASJIM/padctl
Source0:        %{name}-%{version}.tar.gz

ExclusiveArch:  x86_64 aarch64

# Zig 0.16 (shipped in Fedora 44) fails to compile padctl.
# Download Zig 0.15.2 from https://ziglang.org/download/0.15.2/zig-x86_64-linux-0.15.2.tar.xz
# and extract it somewhere, then pass --define 'zig_bin /path/to/zig-0.15.2/zig'
# to rpmbuild. Falls back to just 'zig' if not defined.
%{!?zig_bin: %global zig_bin zig}
BuildRequires:  systemd-rpm-macros
BuildRequires:  coreutils

Requires:       systemd
Requires:       bash
Requires:       util-linux
Requires:       coreutils
Requires:       %{_bindir}/flock

%description
padctl is a HID gamepad compatibility daemon.  It reads declarative
TOML profiles and re-maps gamepad input via uinput, with per-device
systemd socket activation and udev integration.

%prep
%setup -q -n %{name}-%{version}

%build
# Clear Zig cache directories to ensure fresh compilation with source changes.
# Zig caches globally in ~/.cache/zig/ and locally in .zig-cache/ and zig-out/
rm -rf ~/.cache/zig .zig-cache/ zig-out/
%{zig_bin} build -Doptimize=ReleaseSafe -Dtarget=native-native %{?_smp_mflags}

%install
# Run padctl's own installer to generate all files (service, udev rules, scripts).
# --destdir triggers staging mode: no systemctl enable/start, no root checks.
./zig-out/bin/padctl install \
    --destdir %{buildroot} \
    --prefix /usr \
    --no-enable \
    --no-start

# The installer generates a user service under /usr/lib/systemd/user/.
# SupplementaryGroups=input is no longer emitted (a user-scope service manager
# cannot apply it, exit 216/GROUP). Strip it from legacy installs just in case.
sed -i '/^SupplementaryGroups=input$/d' %{buildroot}%{_userunitdir}/padctl.service

# The installer generates a user service under /usr/lib/systemd/user/.
# Create a system-service variant for the RPM so the daemon starts at boot
# without requiring a user session.
# Note: Omit SupplementaryGroups=input — Fedora uses uaccess/ACL instead of
# an input group, and systemd fails with exit code 216/GROUP if the group
# doesn't exist (see commit bd19875c for the user service fix).
mkdir -p %{buildroot}%{_unitdir}
cat > %{buildroot}%{_unitdir}/padctl.service << 'EOF'
[Unit]
Description=padctl gamepad compatibility daemon
After=local-fs.target

[Service]
Type=simple
ExecStart=/usr/bin/padctl
Restart=on-failure
RestartSec=3
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
RuntimeDirectory=padctl
RuntimeDirectoryMode=0755
RuntimeDirectoryPreserve=no
StateDirectory=padctl
DeviceAllow=/dev/hidraw* rw
DeviceAllow=/dev/uinput rw
DeviceAllow=/dev/uhid rw
DeviceAllow=char-input rw

[Install]
WantedBy=multi-user.target
EOF

# Ensure /etc/padctl directories exist for %ghost / runtime use
mkdir -p %{buildroot}/etc/padctl/mappings

%files
%license LICENSE
%{_bindir}/padctl
%{_bindir}/padctl-capture
%{_bindir}/padctl-debug
%{_bindir}/padctl-reconnect
# User service (generated by padctl install)
%{_userunitdir}/padctl.service
# System service (created above)
%{_unitdir}/padctl.service
# Udev rules
%{_udevrulesdir}/60-padctl.rules
%{_udevrulesdir}/61-padctl-driver-block.rules
%{_udevrulesdir}/90-padctl.rules
# Kernel modules load
%{_modulesloaddir}/padctl.conf
# Device config database
%{_datadir}/padctl/
# Runtime config directories
%dir /etc/padctl
%dir /etc/padctl/mappings

%post
%systemd_post padctl.service
# Driver-block udev rules gate on a live daemon control socket
# (/run/user/*/padctl.sock or /run/padctl/padctl.sock) instead of a
# sentinel file. The daemon starts at boot via this system service,
# or via the user service for per-user sessions (enable manually with
#   systemctl --user enable --now padctl.service).
# modules-load.d only loads at next boot; load now so the daemon works first run.
modprobe uhid uinput || true

%preun
%systemd_preun padctl.service
# Remove legacy service-enabled sentinel from pre-socket-gating installs
if [ "$1" -eq 0 ]; then
    rm -f /etc/padctl/service-enabled
fi

%postun
%systemd_postun_with_restart padctl.service

%changelog
* Sat Jun 21 2026 padctl maintainers <maintainers@padctl.dev> - 0.1.17-1
- Fix %%files: use %%{_userunitdir}, %%{_udevrulesdir}, %%{_modulesloaddir} macros
- modprobe uhid uinput in %%post so the daemon works before the next boot

* Sat Jun 13 2026 padctl maintainers <maintainers@padctl.dev> - 0.1.16-1
- Update version to 0.1.16
- Remove libusb1-devel BuildRequires (now vendored as static libusb)
- Remove service-enabled sentinel (udev driver-block rules gate on live daemon socket per commit ec3abe6)
- Add RuntimeDirectoryMode=0755 and RuntimeDirectoryPreserve=no to system service
- Remove destdir sed workaround for udev rules (no longer embed buildroot paths)

* Sun May 17 2026 padctl maintainers <maintainers@padctl.dev> - 0.1.7-1
- Local-build spec: build from source with zig 0.15.2 instead of prebuilt binary
- Add system service unit alongside user service
- Add modules-load.d, 90-padctl.rules, /etc/padctl dirs to %%files
- Add Requires: flock (used by padctl-reconnect)
- Update version to 0.1.7

* Tue May 26 2026 padctl maintainers <maintainers@padctl.dev> - 0.1.12-1
- Update version to 0.1.12
- Add written-by field to service-enabled sentinel for block_kernel_drivers support
