#!/usr/bin/env python3
"""Generate committed Bash and Zsh completions from completions/spec.json."""

from __future__ import annotations

import argparse
import difflib
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "completions" / "spec.json"
BASH_PATH = ROOT / "completions" / "padctl.bash"
ZSH_PATH = ROOT / "completions" / "_padctl"


def nodes(spec: dict) -> list[tuple[str, dict]]:
    result: list[tuple[str, dict]] = [("global", {"options": spec["global_options"]})]
    for command in spec["commands"]:
        result.append((command["name"], command))
        for subcommand in command.get("subcommands", []):
            result.append((f'{command["name"]}/{subcommand["name"]}', subcommand))
    return result


def option_words(node: dict, *, add_help: bool) -> list[str]:
    result = [flag for option in node.get("options", []) for flag in option["flags"]]
    if add_help:
        result.extend(["--help", "-h"])
    return result


def bash_case_function(name: str, entries: list[tuple[str, str]]) -> str:
    lines = [f"{name}()", "{", '    case "$1" in']
    for key, value in entries:
        lines.append(f'        {key}) printf \'%s\\n\' "{value}" ;;')
    lines.extend(["    esac", "}"])
    return "\n".join(lines)


def generate_bash(spec: dict) -> str:
    command_words = " ".join(command["name"] for command in spec["commands"])
    global_words = " ".join(option_words({"options": spec["global_options"]}, add_help=False))

    option_entries: list[tuple[str, str]] = []
    subcommand_entries: list[tuple[str, str]] = []
    positional_entries: list[tuple[str, str]] = []
    value_entries: list[tuple[str, str]] = []
    for context, node in nodes(spec):
        option_entries.append((context, " ".join(option_words(node, add_help=context != "global"))))
        if node.get("subcommands"):
            subcommand_entries.append((context, " ".join(sub["name"] for sub in node["subcommands"])))
        if node.get("positionals"):
            positional_entries.append((context, node["positionals"][0]["value"]))
        for option in node.get("options", []):
            value = option.get("value")
            if value:
                for flag in option["flags"]:
                    value_entries.append((f"{context}:{flag}", value))

    global_value_flags = [
        flag
        for option in spec["global_options"]
        if option.get("value")
        for flag in option["flags"]
    ]
    global_value_pattern = "|".join(global_value_flags)

    metadata = "\n\n".join(
        [
            bash_case_function("_padctl_context_options", option_entries),
            bash_case_function("_padctl_context_subcommands", subcommand_entries),
            bash_case_function("_padctl_context_position_kind", positional_entries),
            bash_case_function("_padctl_value_kind", value_entries),
        ]
    )

    template = r'''# Bash completion for padctl. Generated by scripts/generate-shell-completions.py.

_padctl_complete_files()
{
    local append=${1:-false} candidate
    [[ $append == true ]] || COMPREPLY=()
    while IFS= read -r candidate; do
        COMPREPLY+=("$candidate")
    done < <(compgen -f -- "$cur")
    compopt -o filenames 2>/dev/null || true
}

_padctl_complete_dirs()
{
    local candidate
    COMPREPLY=()
    while IFS= read -r candidate; do
        COMPREPLY+=("$candidate")
    done < <(compgen -d -- "$cur")
    compopt -o filenames 2>/dev/null || true
}

_padctl_complete_words()
{
    COMPREPLY=( $(compgen -W "$1" -- "$cur") )
}

_padctl_add_mapping_reply()
{
    local candidate=$1 existing
    [[ $candidate == "$cur"* ]] || return 0
    for existing in "${COMPREPLY[@]}"; do
        [[ $existing == "$candidate" ]] && return 0
    done
    COMPREPLY+=("$candidate")
}

_padctl_complete_mappings()
{
    local candidate mapping_file
    COMPREPLY=()
    while IFS= read -r candidate; do
        [[ -n $candidate ]] && _padctl_add_mapping_reply "$candidate"
    done < <(command padctl list-mappings --names 2>/dev/null || true)
    for mapping_file in mappings/*.toml; do
        [[ -f $mapping_file ]] || continue
        candidate=${mapping_file##*/}
        _padctl_add_mapping_reply "${candidate%.toml}"
    done
}

_padctl_apply_prefix()
{
    local prefix=$1 i
    [[ -n $prefix ]] || return 0
    for ((i = 0; i < ${#COMPREPLY[@]}; i++)); do
        COMPREPLY[i]="${prefix}${COMPREPLY[i]}"
    done
}

_padctl_complete_value()
{
    local kind=$1 prefix=${2:-} mapping_replies candidate
    case "$kind" in
        file)
            _padctl_complete_files
            ;;
        dir)
            _padctl_complete_dirs
            ;;
        scope)
            _padctl_complete_words "system user package"
            ;;
        mapping)
            _padctl_complete_mappings
            ;;
        mapping_or_file)
            _padctl_complete_mappings
            mapping_replies=$(printf '%s\n' "${COMPREPLY[@]}")
            _padctl_complete_files
            while IFS= read -r candidate; do
                [[ -n $candidate ]] && _padctl_add_mapping_reply "$candidate"
            done <<< "$mapping_replies"
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
    _padctl_apply_prefix "$prefix"
}

__METADATA__

_padctl()
{
    local cur prev command subcommand context word option kind options subcommands option_kind
    local command_index context_start position_seen i
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=""
    if (( COMP_CWORD > 0 )); then
        prev=${COMP_WORDS[COMP_CWORD-1]}
    fi

    command=""
    subcommand=""
    command_index=-1
    for ((i = 1; i < COMP_CWORD; i++)); do
        word=${COMP_WORDS[i]}
        case "$word" in
            --*=*) ;;
            __GLOBAL_VALUE_PATTERN__)
                ((i++))
                ;;
            --doc-gen|--help|-h|--version|-V) ;;
            -*) ;;
            *)
                command=$word
                command_index=$i
                break
                ;;
        esac
    done

    context=${command:-global}
    context_start=$((command_index + 1))
    subcommands=$(_padctl_context_subcommands "$context")
    if [[ -n $subcommands ]] && (( COMP_CWORD > command_index + 1 )); then
        word=${COMP_WORDS[command_index+1]}
        if [[ " $subcommands " == *" $word "* ]]; then
            subcommand=$word
            context="$command/$subcommand"
            context_start=$((command_index + 2))
        fi
    fi

    if [[ $cur == --*=* ]]; then
        option=${cur%%=*}
        kind=$(_padctl_value_kind "$context:$option")
        if [[ -n $kind ]]; then
            cur=${cur#*=}
            _padctl_complete_value "$kind" "$option="
            return
        fi
    fi

    kind=$(_padctl_value_kind "$context:$prev")
    if [[ -n $kind ]]; then
        _padctl_complete_value "$kind"
        return
    fi

    if [[ -z $command ]]; then
        _padctl_complete_words "__COMMAND_WORDS__ __GLOBAL_WORDS__"
        return
    fi

    options=$(_padctl_context_options "$context")
    if [[ -n $subcommands && -z $subcommand ]]; then
        _padctl_complete_words "$subcommands $options"
        return
    fi

    if [[ $cur == -* ]]; then
        _padctl_complete_words "$options"
        return
    fi

    kind=$(_padctl_context_position_kind "$context")
    if [[ -n $kind ]]; then
        position_seen=false
        for ((i = context_start; i < COMP_CWORD; i++)); do
            word=${COMP_WORDS[i]}
            if [[ $word == --*=* ]]; then
                continue
            fi
            option_kind=$(_padctl_value_kind "$context:$word")
            if [[ -n $option_kind ]]; then
                ((i++))
            elif [[ $word != -* ]]; then
                position_seen=true
            fi
        done
        if [[ $position_seen == false ]]; then
            _padctl_complete_value "$kind"
            return
        fi
    fi

    _padctl_complete_words "$options"
}

complete -F _padctl padctl
'''
    return (
        template.replace("__METADATA__", metadata)
        .replace("__GLOBAL_VALUE_PATTERN__", global_value_pattern)
        .replace("__COMMAND_WORDS__", command_words)
        .replace("__GLOBAL_WORDS__", global_words)
    )


ZSH_ACTIONS = {
    "file": "_files",
    "dir": "_directories",
    "scope": "(system user package)",
    "mapping": "_padctl_mapping_names",
    "mapping_or_file": "_padctl_mapping_or_file",
    "plain": "",
}


def zsh_spec(option: dict) -> str:
    flags = option["flags"]
    if set(flags) == {"-h", "--help"}:
        return "'(-h --help)'{-h,--help}'[show help]'"
    if set(flags) == {"-V", "--version"}:
        return "'(-V --version)'{-V,--version}'[show version]'"
    flag = flags[0]
    prefix = "*" if option.get("repeatable") else ""
    result = f"{prefix}{flag}[{option['description']}]"
    value = option.get("value")
    if value:
        label = {
            "file": "file",
            "dir": "directory",
            "scope": "scope",
            "mapping": "mapping name",
            "mapping_or_file": "mapping name or file",
            "plain": option["description"],
        }[value]
        result += f":{label}:{ZSH_ACTIONS[value]}"
    return f"'{result}'"


def zsh_arguments(specs: list[str], indent: str, flags: str = "") -> list[str]:
    if not specs:
        return [f"{indent}_arguments"]
    lines = [f"{indent}_arguments{flags} \\"]
    for index, item in enumerate(specs):
        suffix = " \\" if index + 1 < len(specs) else ""
        lines.append(f"{indent}  {item}{suffix}")
    return lines


def zsh_function_name(context: str) -> str:
    return "_padctl_" + context.replace("-", "_").replace("/", "_")


def zsh_leaf(context: str, node: dict) -> str:
    specs = [zsh_spec(option) for option in node.get("options", [])]
    for index, positional in enumerate(node.get("positionals", []), start=1):
        action = ZSH_ACTIONS[positional["value"]]
        specs.append(f"'{index}:{positional['description']}:{action}'")
    specs.append("'(-h --help)'{-h,--help}'[show help]'")
    lines = [f"{zsh_function_name(context)}() {{"]
    lines.extend(zsh_arguments(specs, "  "))
    lines.append("}")
    return "\n".join(lines)


def zsh_parent(context: str, node: dict) -> str:
    subcommands = node["subcommands"]
    lines = [
        f"{zsh_function_name(context)}() {{",
        "  local context state line",
        "  local -a subcommands",
        "  subcommands=(",
    ]
    for sub in subcommands:
        lines.append(f"    '{sub['name']}:{sub['description']}'")
    lines.extend(
        [
            "  )",
            "  _arguments -C \\",
            "    '1:subcommand:->subcommand' \\",
            "    '*::argument:->arguments' \\",
            "    '(-h --help)'{-h,--help}'[show help]'",
            "  case $state in",
            f"    subcommand) _describe '{context} subcommand' subcommands ;;",
            "    arguments)",
            "      case $line[1] in",
        ]
    )
    for sub in subcommands:
        lines.append(f"        {sub['name']}) {zsh_function_name(context + '/' + sub['name'])} ;;" )
    lines.extend(["      esac", "      ;;", "  esac", "}"])
    return "\n".join(lines)


def generate_zsh(spec: dict) -> str:
    command_descriptions = "\n".join(
        f"  '{command['name']}:{command['description']}'" for command in spec["commands"]
    )
    functions: list[str] = []
    for command in spec["commands"]:
        context = command["name"]
        if command.get("subcommands"):
            for sub in command["subcommands"]:
                functions.append(zsh_leaf(f"{context}/{sub['name']}", sub))
            functions.append(zsh_parent(context, command))
        else:
            functions.append(zsh_leaf(context, command))

    global_specs = [zsh_spec(option) for option in spec["global_options"]]
    global_specs.extend(["'1:command:->command'", "'*::argument:->arguments'"])
    global_arguments = "\n".join(zsh_arguments(global_specs, "  ", " -C"))
    dispatch = "\n".join(
        f"        {command['name']}) {zsh_function_name(command['name'])} ;;"
        for command in spec["commands"]
    )

    return f'''#compdef padctl
# Generated by scripts/generate-shell-completions.py.

local -a padctl_commands
padctl_commands=(
{command_descriptions}
)

_padctl_mapping_names() {{
  local -a mappings local_mappings
  mappings=("${{(@f)$(command padctl list-mappings --names 2>/dev/null)}}")
  local_mappings=(mappings/*.toml(N:t:r))
  mappings+=("${{local_mappings[@]}}")
  (( ${{#mappings}} )) && _describe 'mapping name' mappings
}}

_padctl_mapping_or_file() {{
  _alternative \\
    'mappings:mapping name:_padctl_mapping_names' \\
    'files:mapping file:_files'
}}

{chr(10).join(functions)}

_padctl() {{
  local context state line
{global_arguments}

  case $state in
    command)
      _describe 'padctl command' padctl_commands
      ;;
    arguments)
      case $line[1] in
{dispatch}
      esac
      ;;
  esac
}}

_padctl "$@"
'''


def check_file(path: Path, expected: str) -> bool:
    actual = path.read_text()
    if actual == expected:
        return True
    print(f"generated completion is stale: {path.relative_to(ROOT)}", file=sys.stderr)
    diff = difflib.unified_diff(
        actual.splitlines(),
        expected.splitlines(),
        fromfile=str(path),
        tofile=f"generated:{path.name}",
        lineterm="",
    )
    for line in diff:
        print(line, file=sys.stderr)
    return False


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if committed outputs are stale")
    args = parser.parse_args()

    spec = json.loads(SPEC_PATH.read_text())
    outputs = {
        BASH_PATH: generate_bash(spec),
        ZSH_PATH: generate_zsh(spec),
    }
    if args.check:
        return 0 if all(check_file(path, content) for path, content in outputs.items()) else 1
    for path, content in outputs.items():
        path.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
