# Bash completion for padctl. Generated by scripts/generate-shell-completions.py.

_padctl_complete_files()
{
    local append=${1:-false} candidate
    [[ $append == true ]] || COMPREPLY=()
    while IFS= read -r candidate; do
        COMPREPLY+=("$candidate")
    done < <(compgen -f -- "$cur")
    compopt -o filenames 2>/dev/null || true
}

_padctl_complete_dirs()
{
    local candidate
    COMPREPLY=()
    while IFS= read -r candidate; do
        COMPREPLY+=("$candidate")
    done < <(compgen -d -- "$cur")
    compopt -o filenames 2>/dev/null || true
}

_padctl_complete_words()
{
    COMPREPLY=( $(compgen -W "$1" -- "$cur") )
}

_padctl_add_mapping_reply()
{
    local candidate=$1 existing
    [[ $candidate == "$cur"* ]] || return 0
    for existing in "${COMPREPLY[@]}"; do
        [[ $existing == "$candidate" ]] && return 0
    done
    COMPREPLY+=("$candidate")
}

_padctl_complete_mappings()
{
    local candidate mapping_file
    COMPREPLY=()
    while IFS= read -r candidate; do
        [[ -n $candidate ]] && _padctl_add_mapping_reply "$candidate"
    done < <(command padctl list-mappings --names 2>/dev/null || true)
    for mapping_file in mappings/*.toml; do
        [[ -f $mapping_file ]] || continue
        candidate=${mapping_file##*/}
        _padctl_add_mapping_reply "${candidate%.toml}"
    done
}

_padctl_apply_prefix()
{
    local prefix=$1 i
    [[ -n $prefix ]] || return 0
    for ((i = 0; i < ${#COMPREPLY[@]}; i++)); do
        COMPREPLY[i]="${prefix}${COMPREPLY[i]}"
    done
}

_padctl_complete_value()
{
    local kind=$1 prefix=${2:-} mapping_replies candidate
    case "$kind" in
        file)
            _padctl_complete_files
            ;;
        dir)
            _padctl_complete_dirs
            ;;
        scope)
            _padctl_complete_words "system user package"
            ;;
        mapping)
            _padctl_complete_mappings
            ;;
        mapping_or_file)
            _padctl_complete_mappings
            mapping_replies=$(printf '%s\n' "${COMPREPLY[@]}")
            _padctl_complete_files
            while IFS= read -r candidate; do
                [[ -n $candidate ]] && _padctl_add_mapping_reply "$candidate"
            done <<< "$mapping_replies"
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
    _padctl_apply_prefix "$prefix"
}

_padctl_context_options()
{
    case "$1" in
        global) printf '%s\n' "--config --config-dir --mapping --validate --pid-file --doc-gen --output -h --help -V --version" ;;
        install) printf '%s\n' "--prefix --destdir --immutable --no-immutable --mapping --force-mapping --force-binding --user-service --no-user-service --no-enable --no-start --scope --help -h" ;;
        uninstall) printf '%s\n' "--prefix --destdir --immutable --no-immutable --mapping --scope --help -h" ;;
        scan) printf '%s\n' "--config-dir --help -h" ;;
        list-mappings) printf '%s\n' "--config-dir --names --help -h" ;;
        reload) printf '%s\n' "--pid --help -h" ;;
        switch) printf '%s\n' "--persist --device --socket --help -h" ;;
        output-profile) printf '%s\n' "--help -h" ;;
        output-profile/list) printf '%s\n' "--device --help -h" ;;
        output-profile/select) printf '%s\n' "--device --help -h" ;;
        output-profile/reset) printf '%s\n' "--device --help -h" ;;
        status) printf '%s\n' "--socket --help -h" ;;
        devices) printf '%s\n' "--socket --help -h" ;;
        doctor) printf '%s\n' "--socket --help -h" ;;
        dump) printf '%s\n' "--help -h" ;;
        dump/enable) printf '%s\n' "--socket --help -h" ;;
        dump/disable) printf '%s\n' "--socket --help -h" ;;
        dump/status) printf '%s\n' "--socket --help -h" ;;
        dump/export) printf '%s\n' "--period --socket -o --help -h" ;;
        dump/clear) printf '%s\n' "--socket --help -h" ;;
        config) printf '%s\n' "--help -h" ;;
        config/list) printf '%s\n' "--help -h" ;;
        config/init) printf '%s\n' "--device --help -h" ;;
        config/edit) printf '%s\n' "--help -h" ;;
        config/test) printf '%s\n' "--config --mapping --raw --help -h" ;;
    esac
}

_padctl_context_subcommands()
{
    case "$1" in
        output-profile) printf '%s\n' "list select reset" ;;
        dump) printf '%s\n' "enable disable status export clear" ;;
        config) printf '%s\n' "list init edit test" ;;
    esac
}

_padctl_context_position_kind()
{
    case "$1" in
        switch) printf '%s\n' "mapping" ;;
        output-profile/select) printf '%s\n' "plain" ;;
        config/edit) printf '%s\n' "mapping" ;;
        config/test) printf '%s\n' "mapping_or_file" ;;
    esac
}

_padctl_value_kind()
{
    case "$1" in
        global:--config) printf '%s\n' "file" ;;
        global:--config-dir) printf '%s\n' "dir" ;;
        global:--mapping) printf '%s\n' "mapping_or_file" ;;
        global:--validate) printf '%s\n' "file" ;;
        global:--pid-file) printf '%s\n' "file" ;;
        global:--output) printf '%s\n' "dir" ;;
        install:--prefix) printf '%s\n' "dir" ;;
        install:--destdir) printf '%s\n' "dir" ;;
        install:--mapping) printf '%s\n' "mapping" ;;
        install:--scope) printf '%s\n' "scope" ;;
        uninstall:--prefix) printf '%s\n' "dir" ;;
        uninstall:--destdir) printf '%s\n' "dir" ;;
        uninstall:--mapping) printf '%s\n' "mapping" ;;
        uninstall:--scope) printf '%s\n' "scope" ;;
        scan:--config-dir) printf '%s\n' "dir" ;;
        list-mappings:--config-dir) printf '%s\n' "dir" ;;
        reload:--pid) printf '%s\n' "plain" ;;
        switch:--device) printf '%s\n' "plain" ;;
        switch:--socket) printf '%s\n' "file" ;;
        output-profile/list:--device) printf '%s\n' "plain" ;;
        output-profile/select:--device) printf '%s\n' "plain" ;;
        output-profile/reset:--device) printf '%s\n' "plain" ;;
        status:--socket) printf '%s\n' "file" ;;
        devices:--socket) printf '%s\n' "file" ;;
        doctor:--socket) printf '%s\n' "file" ;;
        dump/enable:--socket) printf '%s\n' "file" ;;
        dump/disable:--socket) printf '%s\n' "file" ;;
        dump/status:--socket) printf '%s\n' "file" ;;
        dump/export:--period) printf '%s\n' "plain" ;;
        dump/export:--socket) printf '%s\n' "file" ;;
        dump/export:-o) printf '%s\n' "file" ;;
        dump/clear:--socket) printf '%s\n' "file" ;;
        config/init:--device) printf '%s\n' "plain" ;;
        config/test:--config) printf '%s\n' "file" ;;
        config/test:--mapping) printf '%s\n' "mapping_or_file" ;;
    esac
}

_padctl()
{
    local cur prev command subcommand context word option kind options subcommands option_kind
    local command_index context_start position_seen i
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=""
    if (( COMP_CWORD > 0 )); then
        prev=${COMP_WORDS[COMP_CWORD-1]}
    fi

    command=""
    subcommand=""
    command_index=-1
    for ((i = 1; i < COMP_CWORD; i++)); do
        word=${COMP_WORDS[i]}
        case "$word" in
            --*=*) ;;
            --config|--config-dir|--mapping|--validate|--pid-file|--output)
                ((i++))
                ;;
            --doc-gen|--help|-h|--version|-V) ;;
            -*) ;;
            *)
                command=$word
                command_index=$i
                break
                ;;
        esac
    done

    context=${command:-global}
    context_start=$((command_index + 1))
    subcommands=$(_padctl_context_subcommands "$context")
    if [[ -n $subcommands ]] && (( COMP_CWORD > command_index + 1 )); then
        word=${COMP_WORDS[command_index+1]}
        if [[ " $subcommands " == *" $word "* ]]; then
            subcommand=$word
            context="$command/$subcommand"
            context_start=$((command_index + 2))
        fi
    fi

    if [[ $cur == --*=* ]]; then
        option=${cur%%=*}
        kind=$(_padctl_value_kind "$context:$option")
        if [[ -n $kind ]]; then
            cur=${cur#*=}
            _padctl_complete_value "$kind" "$option="
            return
        fi
    fi

    kind=$(_padctl_value_kind "$context:$prev")
    if [[ -n $kind ]]; then
        _padctl_complete_value "$kind"
        return
    fi

    if [[ -z $command ]]; then
        _padctl_complete_words "install uninstall scan list-mappings reload switch output-profile status devices doctor dump config --config --config-dir --mapping --validate --pid-file --doc-gen --output -h --help -V --version"
        return
    fi

    options=$(_padctl_context_options "$context")
    if [[ -n $subcommands && -z $subcommand ]]; then
        _padctl_complete_words "$subcommands $options"
        return
    fi

    if [[ $cur == -* ]]; then
        _padctl_complete_words "$options"
        return
    fi

    kind=$(_padctl_context_position_kind "$context")
    if [[ -n $kind ]]; then
        position_seen=false
        for ((i = context_start; i < COMP_CWORD; i++)); do
            word=${COMP_WORDS[i]}
            if [[ $word == --*=* ]]; then
                continue
            fi
            option_kind=$(_padctl_value_kind "$context:$word")
            if [[ -n $option_kind ]]; then
                ((i++))
            elif [[ $word != -* ]]; then
                position_seen=true
            fi
        done
        if [[ $position_seen == false ]]; then
            _padctl_complete_value "$kind"
            return
        fi
    fi

    _padctl_complete_words "$options"
}

complete -F _padctl padctl
